### ISSUE TITLE
Binding Ritual crashed game

### ISSUE THREAD

**Issue by CammiePone** [MoriyaShiine/bewitchment#10]
I'm guessing it's because the frog hopped away.

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/25/21, 10:44 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.nbt.NbtHelper.toUuid(NbtHelper.java:182)
	at net.minecraft.nbt.CompoundTag.getUuid(CompoundTag.java:107)
	at moriyashiine.bewitchment.common.ritualfunction.BindFamiliarRitualFunction.start(BindFamiliarRitualFunction.java:63)
	at moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity.tick(GlyphBlockEntity.java:144)
	at net.minecraft.world.World.tickBlockEntities(World.java:450)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:370)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:804)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:79)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:662)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:227)
	at java.base/java.lang.Thread.run(Thread.java:834)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.NbtHelper.toUuid(NbtHelper.java:182)
	at net.minecraft.nbt.CompoundTag.getUuid(CompoundTag.java:107)
	at moriyashiine.bewitchment.common.ritualfunction.BindFamiliarRitualFunction.start(BindFamiliarRitualFunction.java:63)
	at moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity.tick(GlyphBlockEntity.java:144)

-- Block entity being ticked --
Details:
	Name: bewitchment:glyph // moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity
	Block: Block{bewitchment:golden_glyph}[age=0,facing=west]
	Block location: World: (257,71,222), Chunk: (at 1,4,14 in 16,13; contains blocks 256,0,208 to 271,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{bewitchment:golden_glyph}[age=0,facing=west]
	Block location: World: (257,71,222), Chunk: (at 1,4,14 in 16,13; contains blocks 256,0,208 to 271,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.tickBlockEntities(World.java:450)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:370)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player148'/182, l='ServerLevel[New World]', x=261.14, y=71.61, z=222.67]]
	Chunk stats: ServerChunkCache: 3025
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,73,224), Chunk: (at 0,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 40004 game time, 1927 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 48544 (now: false), thunder time: 111405 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:804)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:79)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:662)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:227)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2701548752 bytes (2576 MB) / 3617587200 bytes (3450 MB) up to 8558477312 bytes (8162 MB)
	CPUs: 12
	JVM Flags: 0 total; 
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bewitchment: Bewitchment 1.16.5-1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		dt: Damage Threshold 1.2
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		java: OpenJDK 64-Bit Server VM 11
		minecraft: Minecraft 1.16.5
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.8.11
		roughlyenoughitems-api: REI (API) 5.8.11
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.11
		roughlyenoughitems-runtime: REI (Runtime) 5.8.11
		strawdummy: Straw Dummy 1.4.0
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
	Player Count: 1 / 8; [ServerPlayerEntity['Player148'/182, l='ServerLevel[New World]', x=261.14, y=71.61, z=222.67]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'```

**Comment by CammiePone** [comment]
okay it wasn't because it wasn't inside the circle. not sure why it crashed, unless the toad needs to be tamed for that

**Comment by CammiePone** [comment]
yep it's because it wasn't tamed. you should probably fix that.
