### ISSUE TITLE
The Cocoa Bean Crash

### ISSUE THREAD

**Issue by benjamini999** [MoriyaShiine/bewitchment#103]
In the current version of the mod. using the propogation ritual near cocoa beans causes the game to crash continously. 
See crash report below:-
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2]} to 3 on Block{minecraft:cocoa}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:122)
	at net.minecraft.class_2282.method_9652(class_2282.java:144)
	at moriyashiine.bewitchment.common.ritualfunction.GrowRitualFunction.tick(GrowRitualFunction.java:35)
	at moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity.method_16896(GlyphBlockEntity.java:142)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5353/74702912.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:122)
	at net.minecraft.class_2282.method_9652(class_2282.java:144)
	at moriyashiine.bewitchment.common.ritualfunction.GrowRitualFunction.tick(GrowRitualFunction.java:35)
	at moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity.method_16896(GlyphBlockEntity.java:142)

-- Block entity being ticked --
Details:
	Name: bewitchment:glyph // moriyashiine.bewitchment.common.block.entity.GlyphBlockEntity
	Block: Block{bewitchment:golden_glyph}[age=2,facing=north]
	Block location: World: (77,68,851), Chunk: (at 13,4,3 in 4,53; contains blocks 64,0,848 to 79,255,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Block: Block{bewitchment:golden_glyph}[age=2,facing=north]
	Block location: World: (77,68,851), Chunk: (at 13,4,3 in 4,53; contains blocks 64,0,848 to 79,255,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Benjamini999'/70, l='ServerLevel[New World]', x=63.63, y=68.00, z=854.10]]
	Chunk stats: ServerChunkCache: 2982
	Level dimension: minecraft:overworld
	Level spawn location: World: (-30,63,4), Chunk: (at 2,3,4 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1677580 game time, 625903 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 8611 (now: true), thunder time: 12841 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5353/74702912.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 591951104 bytes (564 MB) / 1981808640 bytes (1890 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bewitchment: Bewitchment 1.16.5-8
		blue_endless_jankson: jankson 1.2.0
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		couplings: Couplings 1.3.3
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallingtree: FallingTree 2.11.0
		fiber: fiber 0.23.0-2
		gravestones: Gravestones v1.9
		impersonate: Impersonate 2.1.0
		inventorysorter: Inventory Sorter 1.7.9-1.16
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kyrptconfig: Kytpt Config 1.1.6-1.16
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		minecraft: Minecraft 1.16.5
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.0.0+21w14a
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simple_backpack: SimpleBackpack 1.0.38
		simplexterrain: Simplex Terrain 0.7.2
		somnus: Somnus API 0.0.11-1.16.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		trinkets: Trinkets 2.6.7
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['Benjamini999'/70, l='ServerLevel[New World]', x=63.63, y=68.00, z=854.10]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by benjamini999** [comment]
I'm unable to even load into the world because the ritual is ongoing. So i can't stop the ritual
