### ISSUE TITLE
Minecraft crashes when putting in the cloth dependency (No fabric window, exit code 0 no crash log.)

### ISSUE THREAD

**Issue by TheFurru** [MoriyaShiine/bewitchment#133]
I put the cloth dependency in the mods folder, start up fabric to see the next dependency via the error, and no fabric window pops up. (im using the latest of every dependency, i put cloth in last.)
Crashes. No fabric window, exit code 0, no crash log for some reason.

**Comment by MoriyaShiine** [comment]
I need the latest.log if there's no crash report

**Comment by TheFurru** [comment]
> I need the latest.log if there's no crash report

And where do i find that?

**Comment by MoriyaShiine** [comment]
In your logs folder

**Comment by TheFurru** [comment]
Okay.
 [20:29:10] [main/INFO]: Loading for game Minecraft 1.16.5
[20:29:11] [ForkJoinPool-1-worker-10/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[20:29:11] [ForkJoinPool-1-worker-8/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[20:29:11] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[20:29:11] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[20:29:11] [main/INFO]: [FabricLoader] Loading 69 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.11.218, step-height-entity-attribute@1.0.0, fabricloader@0.11.1, trinkets@2.6.7, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, fabric-permissions-api-v0@0.1-SNAPSHOT, pehkui@2.1.0+21w18a, java@8, impersonate@2.2.1, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, bewitchment@1.16.5-12, fiber@0.23.0-2, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.1.1, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, terraform-wood-api-v1@1.0.4, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.34.2+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, roughlyenoughitems-default-plugin@5.11.218, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, roughlyenoughitems-runtime@5.11.218, cloth-client-events-v0@1.5.47, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, roughlyenoughitems@5.11.218, somnus@${version}, fabric-entity-events-v1@1.1.0+c88702897d, patchouli@1.16.4-50-FABRIC, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, cloth-config2@4.10.13, nourish@1.2.1, fabric-resource-loader-v0@0.4.6+2868a2287d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.8.2, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.8.2, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.3+e3c9d0627d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[20:29:11] [main/WARN]: Mod `somnus` (${version}) does not respect SemVer - comparison support is limited.
[20:29:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jfryp/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[20:29:11] [main/FATAL]: Mixin prepare failed preparing MixinBedBlock in somnus.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'top.theillusivec4.somnus.mixin.MixinBedBlock' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'top.theillusivec4.somnus.mixin.MixinBedBlock' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.1.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'top.theillusivec4.somnus.mixin.MixinBedBlock' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	... 15 more

**Comment by TheFurru** [comment]
[latest.log](https://github.com/MoriyaShiine/bewitchment/files/6488471/latest.log)


or do you need this?

**Comment by MoriyaShiine** [comment]
This isn't a bewitchment bug, this is caused by somnus somehow. I'd recommend redownloading it since the version isn't specified.

**Comment by TheFurru** [comment]
0.0.11 is somnus. sorry about earlier. didnt include it.
