### ISSUE TITLE
crashing when I load singleplayer

### ISSUE THREAD

**Issue by jebowles1** [MoriyaShiine/bewitchment#135]
I downloaded bewitchment-1.16.5-12 after I've been using 1.16.5-11 and it finishes loading the world then crashes 

Time: 5/17/21 3:26 PM
Description: Ticking block entity

java.lang.ClassCastException: moriyashiine.bewitchment.api.BewitchmentAPI$1 cannot be cast to net.minecraft.class_3222
	at ru.betterend.blocks.basis.StrippableBarkBlock.method_9534(StrippableBarkBlock.java:34)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.scan(WitchAltarBlockEntity.java:195)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.method_16896(WitchAltarBlockEntity.java:99)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7709/1912696670.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ru.betterend.blocks.basis.StrippableBarkBlock.method_9534(StrippableBarkBlock.java:34)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.scan(WitchAltarBlockEntity.java:195)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.method_16896(WitchAltarBlockEntity.java:99)

-- Block entity being ticked --
Details:
	Name: bewitchment:witch_altar // moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity
	Block: Block{bewitchment:purple_blackstone_witch_altar}[facing=south,level=0,waterlogged=false]
	Block location: World: (-5416,82,2810), Chunk: (at 8,5,10 in -339,175; contains blocks -5424,0,2800 to -5409,255,2815), Region: (-11,5; contains chunks -352,160 to -321,191, blocks -5632,0,2560 to -5121,255,3071)
	Block: Block{bewitchment:purple_blackstone_witch_altar}[facing=south,level=0,waterlogged=false]
	Block location: World: (-5416,82,2810), Chunk: (at 8,5,10 in -339,175; contains blocks -5424,0,2800 to -5409,255,2815), Region: (-11,5; contains chunks -352,160 to -321,191, blocks -5632,0,2560 to -5121,255,3071)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Sully914'/156, l='ServerWorld minecraft:overworld enderboi', x=-5565.51, y=101.98, z=2839.47]]
	Chunk stats: ServerChunkCache: 4050
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,82,-160), Chunk: (at 0,5,0 in -8,-10; contains blocks -128,0,-160 to -113,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 531979 game time, 461135 day time
	Level name: enderboi
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 101412 (now: false), thunder time: 118664 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7709/1912696670.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3156628448 bytes (3010 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods:

**Comment by MoriyaShiine** [comment]
clone of https://github.com/MoriyaShiine/bewitchment/issues/134

**Comment by jebowles1** [comment]
how do I fix it tho I am new to mods and the fix link makes no sense to me

**Comment by MoriyaShiine** [comment]
You update, a release was made literally 30 minutes ago
