### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#187]
latest version of mod and 1.17.1 fabric

java.lang.RuntimeException: Error building entry bewitchment:rituals/binding
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:88) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:84) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:122) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:35) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at net.minecraft.client.network.ClientAdvancementManager.handler$flg000$patchouli_onSync(ClientAdvancementManager:1018) ~[?:?]
	at net.minecraft.client.network.ClientAdvancementManager.onAdvancements(ClientAdvancementManager:57) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onAdvancements(ClientPlayNetworkHandler:1204) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:51) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry bewitchment:rituals/binding page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:223) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:86) ~[Patchouli-1.17-54-FABRIC.jar:?]
	... 26 more
Caused by: java.lang.RuntimeException: Error setting up template processor
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:96) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:220) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:86) ~[Patchouli-1.17-54-FABRIC.jar:?]
	... 26 more
Caused by: java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at moriyashiine.bewitchment.client.integration.patchouli.RitualProcessor.setup(RitualProcessor.java:23) ~[bewitchment-1.17-3.jar:?]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:94) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:220) ~[Patchouli-1.17-54-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:86) ~[Patchouli-1.17-54-FABRIC.jar:?]
	... 26 more

**Comment by MoriyaShiine** [comment]
Can't reproduce, and impossible to tell if latest because half of the report isn't here (there's a reason devs hate "latest" :p). Try updating all of your mods, and if that doesn't work, binary search and report to Patchouli.

**Comment by red2blue** [comment]
I apologize I didn't remember posting this. So I updated all mods, and still got this. I'll reach out to patchouli
