### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by avedium** [MoriyaShiine/bewitchment#188]
Recently installed bewitchment on a fresh installation on Fabric to try it out, but my game keeps crashing before loading the main menu screen. I'm running the latest version. No error messages, and I've already trialed and errored by individually removing all the mods. Here's the log file: 

[01:50:19] [main/INFO]: Loading for game Minecraft 1.17.1
[01:50:20] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b4463d5, 0.3.0+a02b446318
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afa13, also found 0.3.2+92519afa18
[01:50:20] [main/INFO]: [FabricLoader] Loading 74 mods:
	- bewitchment@1.17-3
	- cardinal-components@3.1.1
	- cardinal-components-base@3.1.1
	- cardinal-components-block@3.1.1
	- cardinal-components-chunk@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-item@3.1.1
	- cardinal-components-level@3.1.1
	- cardinal-components-scoreboard@3.1.1
	- cardinal-components-util@3.1.1
	- cardinal-components-world@3.1.1
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- fabric@0.38.2+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
	- fabric-biome-api-v1@3.1.12+3fe74aa118
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.4+2e8bd82f18
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.7.0+2e8bd82f18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.0+3fe74aa118
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.1.2+8195aec118
	- fabricloader@0.11.6
	- fiber@0.23.0-2
	- impersonate@2.3.3
	- java@16
	- kanos_config@0.1.4+1.14.4-1.17.1
	- minecraft@1.17.1
	- patchouli@1.16.4-53-FABRIC
	- pehkui@2.3.0+1.14.4-1.17.1
	- playerabilitylib@1.3.0
	- reach-entity-attributes@2.1.1
	- roughlyenoughitems@6.0.268-alpha
	- somnus@0.0.12-1.17
	- step-height-entity-attribute@1.0.0
	- terraform-wood-api-v1@2.0.2
	- trinkets@3.0.2
[01:50:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Avery/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[01:50:20] [main/INFO]: Compatibility level set to JAVA_16
[01:50:20] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[01:50:21] [main/WARN]: Error loading class: io/github/apace100/apoli/power/PreventItemUsePower (java.lang.ClassNotFoundException: io/github/apace100/apoli/power/PreventItemUsePower)
[01:50:21] [main/WARN]: @Mixin target io.github.apace100.apoli.power.PreventItemUsePower was not found bewitchment.mixins.json:integration.origins.PreventItemUsePowerMixin
[01:50:21] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
[01:50:21] [main/FATAL]: Mixin apply failed patchouli.mixins.json:client.MixinCrashReport -> net.minecraft.class_128: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_567 in patchouli.mixins.json:client.MixinCrashReport was not located in the target class net.minecraft.class_128. Using refmap Patchouli-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_567 in patchouli.mixins.json:client.MixinCrashReport was not located in the target class net.minecraft.class_128. Using refmap Patchouli-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:423) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]``

**Comment by MoriyaShiine** [comment]
You're using the 1.16 version of patchouli, I'd recommend updating lol
