### ISSUE TITLE
NBTCrafting?

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#189]
Does Bewitchment attempt to use NBTCrafting?

I have seen this in my server logs and ever since I added bewitchment REI is not working

java.lang.NullPointerException: Server player entity cannot be null
at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.canSend(ServerPlayNetworking.java:182) ~[7a765ea2-65d9-4e5f-af3b-c0807a57b5cd.jar:?]
at de.siphalor.nbtcrafting.NbtCrafting.hasClientMod(NbtCrafting.java:142) ~[85c3bd16-dc88-4f9c-82c9-9776ac265c16.jar:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.handler$zoi000$onWrite(SynchronizeRecipesS2CPacket:541) ~[?:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket) ~[?:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.handler$bni000$replaceRecipesOnClient(SynchronizeRecipesS2CPacket:1049) ~[?:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.getRecipes(SynchronizeRecipesS2CPacket) ~[?:?]
at net.minecraft.client.network.ClientPlayNetworkHandler.onSynchronizeRecipes(ClientPlayNetworkHandler:1240) ~[?:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:32) ~[?:?]
at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:14) ~[?:?]
at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

**Comment by MoriyaShiine** [comment]
No, Bewitchment does not depend on NBTCrafting
