### ISSUE TITLE
For some reason i cant seem to run the mod, I keep getting this same error message

### ISSUE THREAD

**Issue by DumCumpster** [MoriyaShiine/bewitchment#227]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 12/2/21, 1:20 AM
Description: Unexpected error

java.lang.NoSuchMethodError: 'moriyashiine.bewitchment.api.component.TransformationComponent moriyashiine.bewitchment.api.component.TransformationComponent.get(net.minecraft.class_1657)'
	at com.williambl.haema.compat.bewitchment.BewitchmentIntegrationKt$registerBewitchmentEventListeners$7.onTransformationSet(BewitchmentIntegrationKt.java:76)
	at moriyashiine.bewitchment.api.event.OnTransformationSet.lambda$static$0(OnTransformationSet.java:12)
	at moriyashiine.bewitchment.api.component.TransformationComponent.setTransformation(TransformationComponent.java:141)
	at moriyashiine.bewitchment.api.component.TransformationComponent.readFromNbt(TransformationComponent.java:61)
	at dev.onyxstudios.cca.api.v3.component.sync.AutoSyncedComponent.applySyncPacket(AutoSyncedComponent.java:101)
	at dev.onyxstudios.cca.internal.entity.CcaEntityClientNw.lambda$initClient$1(CcaEntityClientNw.java:52)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.onyxstudios.cca.internal.entity.CcaEntityClientNw.lambda$initClient$2(CcaEntityClientNw.java:52)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.class_310.method_1523(class_310.java:1075)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.williambl.haema.compat.bewitchment.BewitchmentIntegrationKt$registerBewitchmentEventListeners$7.onTransformationSet(BewitchmentIntegrationKt.java:76)
	at moriyashiine.bewitchment.api.event.OnTransformationSet.lambda$static$0(OnTransformationSet.java:12)
	at moriyashiine.bewitchment.api.component.TransformationComponent.setTransformation(TransformationComponent.java:141)
	at moriyashiine.bewitchment.api.component.TransformationComponent.readFromNbt(TransformationComponent.java:61)
	at dev.onyxstudios.cca.api.v3.component.sync.AutoSyncedComponent.applySyncPacket(AutoSyncedComponent.java:101)
	at dev.onyxstudios.cca.internal.entity.CcaEntityClientNw.lambda$initClient$1(CcaEntityClientNw.java:52)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at dev.onyxstudios.cca.internal.entity.CcaEntityClientNw.lambda$initClient$2(CcaEntityClientNw.java:52)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)

-- Affected level --
Details:
	All players: 1 total; [class_746['BejitaBadman'/622, l='ClientLevel', x=287.50, y=65.00, z=271.50]]
	Chunk stats: 625, 400
	Level dimension: minecraft:overworld
	Level spawn location: World: (288,66,272), Section: (at 0,2,0 in 18,4,17; chunk contains blocks 288,0,272 to 303,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3 game time, 3 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1078665424 bytes (1028 MiB) / 2550136832 bytes (2432 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=26.20.14054.1001
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 3072.00
	Graphics card #1 deviceId: 0x1c91
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6280
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14524.41
	Virtual memory used (MB): 11524.31
	Swap memory total (MB): 8503.27
	Swap memory used (MB): 908.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.5+mc21w16a
		architectury: Architectury 2.6.35
		backslot: BackSlot 1.2.2
		besmirchment: Besmirchment 1.17.1-7
		bewitchment: Bewitchment 1.17-16
		bountiful: Bountiful 2.0.2
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.1.40
		collective-fabric: Collective (Fabric) 3.9
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		cosmetica: Cosmetica 0.3.1
		diamold: Diamold 1.3.2+1.17.1
		dungeons_arise: When Dungeons Arise 2.1.49-fabric
		enchant_giver: Enchant Giver 1.1.0
		enhancedcelestials: Enhanced Celestials 2.0.6
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.5
		fallingtree: FallingTree 2.14.3
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.29
		goosik-config: goosik-config 0.1.1
		graveyard: The Graveyard 2.1
		haema: Haema 1.7.7+1.17
		hwg: Happiness is a Warm Gun 1.0.25
		impersonate: Impersonate 2.3.5
		java: OpenJDK 64-Bit Server VM 16
		kambrik: Kambrik 2.4.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libcd: LibCapableData 3.0.3+1.16.3
		mcda: MC Dungeons Armors 1.7.15
		mcdw: MC Dungeons Weapons 3.6.0
		minecraft: Minecraft 1.17.1
		mostructures: Mo' Structures 1.2.1-1.17
		neutrino: Neutrino 0.6.3
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		owo: oωo 0.3.2+1.17
		patchouli: Patchouli 1.17.1-59-FABRIC
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		playerabilitylib: Pal 1.4.0
		pugh_lib: Pugh Lib ${version}
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		resourceful_tools: Resourceful Tools 1.1.23
		roughlyenoughitems: Roughly Enough Items 6.1.327
		satin: Satin 1.6.1
		simple_backpack: SimpleBackpack 1.1.20
		somnus: Somnus API 0.0.14-1.17.1
		spellbound: Spellbound 1.6.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		trinkets: Trinkets 3.0.4
		victus: Victus 0.1.3+1.17.1
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		visuality: Visuality 0.3.2
	Launched Version: fabric-loader-0.12.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 462.80, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 
	Player Count: 1 / 8; [class_3222['BejitaBadman'/622, l='ServerLevel[.]', x=287.50, y=65.00, z=271.50]]
	Data Packs: vanilla, Fabric Mods

**Comment by MoriyaShiine** [comment]
Haema hasn't updated integration on their end, there's a PR for it on their github iirc
