### ISSUE TITLE
Getting this crash with bewitchment-1.16.5-18.jar.

### ISSUE THREAD

**Issue by jimmytrouser** [MoriyaShiine/bewitchment#240]
Getting this crash with bewitchment-1.16.5-18.jar.  I downloaded Bewitchment using curseforge and added no other mods, only the ones it recommends.  Can't even start the game.  I realise this is the 1.16.5 version so any help would be greatly appreciated.

Fabric loader 0.12.12
bewitchment-1.16.5-18.jar
cloth-config-4.13.49-fabric.jar
fabric-api-0.42.0+1.16.jar
Impersonate-2.2.1.jar
Patchouli-1.16.4-53-FABRIC.jar
Pehkui-3.1.0+1.14.4-1.18.1.jar
somnus-fabric-0.0.12-1.16.5.jar
trinkets-2.6.7.jar

---- Minecraft Crash Report ----
// There are four lights!

Time: 1/1/22 10:11 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2323/144084968.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: WIDTH
	at moriyashiine.bewitchment.common.registry.BWScaleTypes.init(BWScaleTypes.java:24)
	at moriyashiine.bewitchment.common.Bewitchment.onInitialize(Bewitchment.java:220)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2232/486675606.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2323/144084968.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 160018992 bytes (152 MB) / 2330460160 bytes (2222 MB) up to 7456948224 bytes (7111 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m
	Fabric Mods: 
		bewitchment: Bewitchment 1.16.5-18
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v4 4.13.49
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.12
		fiber: fiber 0.23.0-2
		impersonate: Impersonate 2.2.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		minecraft: Minecraft 1.16.5
		patchouli: Patchouli 1.16.4-53-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		somnus: Somnus API 0.0.12-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		trinkets: Trinkets 2.6.7
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.12.12-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by MoriyaShiine** [comment]
Clone of https://github.com/MoriyaShiine/bewitchment/issues/230
