### ISSUE TITLE
Bewitchment + RatLab Conflict (Crashes Game w/ Ticking Entity Error)

### ISSUE THREAD

**Issue by Eaglecrye** [MoriyaShiine/bewitchment#245]
For a while, I thought I could only really bring up the issue in the Discord community from RatLab's creator (since it's a paid/private mod, therefore there's no public repo), BUT I'm going to try my hand at bringing it up here too just incase.

When used alongside the **RatLab** mod, the game crashes with a "Ticking Entity" error before the world loads in. The _"Not Enough Crashes"_ mod initially only blamed Trinket's "Step Height Entity Attribute" library, but after a quick fix by Doctor4T, it STILL crashes but now also includes RatLab as a culprit. It's not a pure conflict with Trinkets however, because if I remove either RatLab or Bewitchment and keep Trinkets in, the game doesn't crash. I tried everything I could, even at one point removing Sodium and using the bare essentials needed to run Fabric and both RatLab and Bewitchment. I got the crash report too:

```
---- Minecraft Crash Report ----
// Why did you do that?
 
Time: 1/18/22, 1:47 AM
Description: Ticking entity
 
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1324.method_6194()" because the return value of "net.minecraft.class_1309.method_5996(net.minecraft.class_1320)" is null
	at dev.emi.stepheightentityattribute.StepHeightEntityAttributeMain.getStepHeight(StepHeightEntityAttributeMain.java:18)
	at net.minecraft.entity.Entity.redirect$can000$getStepHeight(Entity:11486)
	at net.minecraft.entity.Entity.adjustMovementForCollisions(Entity:908)
	at net.minecraft.entity.Entity.move(Entity:633)
	at net.minecraft.entity.LivingEntity.applyMovementInput(LivingEntity:2247)
	at net.minecraft.entity.LivingEntity.travel(LivingEntity:2192)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2643)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:545)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:345)
	at ratlab.common.entity.AllayEntity.tick(AllayEntity.java:130)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:699)
	at net.minecraft.world.World.tickEntity(World:487)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:360)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:328)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at dev.emi.stepheightentityattribute.StepHeightEntityAttributeMain.getStepHeight(StepHeightEntityAttributeMain.java:18)
	at net.minecraft.class_1297.redirect$can000$getStepHeight(class_1297.java:11486)
	at net.minecraft.class_1297.method_17835(class_1297.java:908)
	at net.minecraft.class_1297.method_5784(class_1297.java:633)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at ratlab.common.entity.AllayEntity.method_5773(AllayEntity.java:130)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
 
-- Entity being ticked --
Details:
	Entity Type: ratlab:allay (ratlab.common.entity.AllayEntity)
	Entity ID: 1
	Entity Name: entity.ratlab.allay
	Entity's Exact location: -15.39, 129.00, -43.23
	Entity's Block location: World: (-16,129,-44), Section: (at 0,1,4 in -1,8,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.30000001192092896d,Name:"minecraft:generic.movement_speed"},{Base:48.0d,Modifiers:[{Amount:0.031019013185617717d,Name:"Random spawn bonus",Operation:1,UUID:[I;-1885658629,-1376368508,-1158335378,962989774]}],Name:"minecraft:generic.follow_range"}],Brain:{memories:{}},CanPickUpLoot:1b,DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:10.0f,HurtByTimestamp:0,HurtTime:0s,Invulnerable:0b,LeftHanded:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[-15.390703395718365d,129.0d,-43.22665423297808d],Rotation:[0.0f,0.0f],UUID:[I;1075652324,-2052963779,-2145090882,619646910],cardinal_components:{"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0},"bewitchment:blood":{Blood:100},"bewitchment:curses":{Curses:[]},"bewitchment:fake_mob":{TargetUUID:""},"bewitchment:familiar":{Familiar:0b},"bewitchment:minion":{MasterUUID:""}}}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,124,-48), Section: (at 0,12,0 in -1,7,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 23358 game time, 23358 day time
	Level name: Rat2
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 28567 (now: false), thunder time: 123668 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2124398576 bytes (2025 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Graphics card #1 name: Insignia USB3.0 To VGA Adapter
	Graphics card #1 vendor: Insignia (0x19ff)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x562a
	Graphics card #1 versionInfo: DriverVersion=1.4.2101.1112
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 43644.22
	Virtual memory used (MB): 38078.78
	Swap memory total (MB): 27426.64
	Swap memory used (MB): 3667.50
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		architectury: Architectury 3.4.9
		bewitchment: Bewitchment 1.18-6
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.26
		impersonate: Impersonate 2.4.0
		indium: Indium 1.0.2-alpha2+mc1.18.1
		iris: Iris 1.2.0-pre+rev.cc2d93e-dirty
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		patchouli: Patchouli 1.18.1-64-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.5.0
		ratlab: RatLab 1.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 7.1.390
		satin: Satin 1.7.2
		sodium: Sodium 0.4.0-alpha6+build.14
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		trinkets: Trinkets 3.1.0
		wthit: wthit 4.4.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), RatLab (ratlab), Step Height Entity Attribute (step-height-entity-attribute)

```

**Comment by MoriyaShiine** [comment]
Can I have the new crash? If it crashes in the same spot then I can't do anything about it, Step Height Entity Attributes expects mobs to call LivingEntity#createLivingAttributes

**Comment by Eaglecrye** [comment]
Oh boy. Yeah, I can provide the report right here, sure. If it is the same spot though, I'd just be wondering how it _could_ be solved on the other end.
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/18/22, 12:28 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1324.method_6194()" because the return value of "net.minecraft.class_1309.method_5996(net.minecraft.class_1320)" is null
	at dev.emi.stepheightentityattribute.StepHeightEntityAttributeMain.getStepHeight(StepHeightEntityAttributeMain.java:18)
	at net.minecraft.entity.Entity.redirect$can000$getStepHeight(Entity:11486)
	at net.minecraft.entity.Entity.adjustMovementForCollisions(Entity:908)
	at net.minecraft.entity.Entity.move(Entity:633)
	at net.minecraft.entity.LivingEntity.applyMovementInput(LivingEntity:2247)
	at net.minecraft.entity.LivingEntity.travel(LivingEntity:2192)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2643)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:545)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:58)
	at net.minecraft.entity.passive.SheepEntity.tickMovement(SheepEntity:139)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:345)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:699)
	at net.minecraft.world.World.tickEntity(World:487)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:360)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:328)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.emi.stepheightentityattribute.StepHeightEntityAttributeMain.getStepHeight(StepHeightEntityAttributeMain.java:18)
	at net.minecraft.class_1297.redirect$can000$getStepHeight(class_1297.java:11486)
	at net.minecraft.class_1297.method_17835(class_1297.java:908)
	at net.minecraft.class_1297.method_5784(class_1297.java:633)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1472.method_6007(class_1472.java:139)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: minecraft:sheep (net.minecraft.class_1472)
	Entity ID: 4
	Entity Name: Sheep
	Entity's Exact location: 45.00, 96.00, 39.00
	Entity's Block location: World: (45,96,39), Section: (at 13,0,7 in 2,6,2; chunk contains blocks 32,-64,32 to 47,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Age:0,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:16.0d,Modifiers:[{Amount:0.029821953792681273d,Name:"Random spawn bonus",Operation:1,UUID:[I;-50834848,80953367,-1778884486,-1801779417]}],Name:"minecraft:generic.follow_range"},{Base:0.23000000417232513d,Name:"minecraft:generic.movement_speed"}],Brain:{memories:{}},CanPickUpLoot:0b,Color:7b,DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,ForcedAge:0,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:8.0f,HurtByTimestamp:0,HurtTime:0s,InLove:0,Invulnerable:0b,LeftHanded:0b,Motion:[0.0d,0.0d,0.0d],OnGround:0b,PersistenceRequired:0b,PortalCooldown:0,Pos:[45.0d,96.0d,39.0d],Rotation:[106.155075f,0.0f],Sheared:0b,UUID:[I;-1586270008,883771639,-1377834405,2126674966],cardinal_components:{"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0},"bewitchment:blood":{Blood:100},"bewitchment:curses":{Curses:[]},"bewitchment:fake_mob":{TargetUUID:""},"bewitchment:familiar":{Familiar:0b},"bewitchment:minion":{MasterUUID:""}}}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,108,0), Section: (at 0,12,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1 game time, 1 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 35811 (now: false), thunder time: 125076 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2173955592 bytes (2073 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Graphics card #1 name: Insignia USB3.0 To VGA Adapter
	Graphics card #1 vendor: Insignia (0x19ff)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x562a
	Graphics card #1 versionInfo: DriverVersion=1.4.2101.1112
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 45238.99
	Virtual memory used (MB): 40566.38
	Swap memory total (MB): 29021.41
	Swap memory used (MB): 4412.63
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		architectury: Architectury 3.4.9
		bewitchment: Bewitchment 1.18-6
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.26
		impersonate: Impersonate 2.4.0
		indium: Indium 1.0.2-alpha2+mc1.18.1
		iris: Iris 1.2.0-pre+rev.cc2d93e-dirty
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		patchouli: Patchouli 1.18.1-64-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.5.0
		ratlab: RatLab 1.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 7.1.390
		satin: Satin 1.7.2
		sodium: Sodium 0.4.0-alpha6+build.14
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		trinkets: Trinkets 3.1.0
		wthit: wthit 4.4.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), Step Height Entity Attribute (step-height-entity-attribute)
```

**Comment by MoriyaShiine** [comment]
Yep, that's the same spot. I have no idea why it would be crashing there, but I'd report to https://github.com/emilyploszaj/step-height-entity-attribute. Very odd that even sheep crash the game.
