### ISSUE TITLE
Getting dced while riding the elder broom

### ISSUE THREAD

**Issue by Hallowedz** [MoriyaShiine/bewitchment#314]
### Mod version

bewitchment 1.19-4 

### A description of the issue

was flying around on elder broom fine then all of the sudden the game decided it didnt like that and instant boots me the moment i try to move on the broom
![image](https://user-images.githubusercontent.com/97772561/182746603-1b07ee13-ddcc-4432-9458-54804c8c429f.png)

**Comment by MoriyaShiine** [comment]
I need a log

**Comment by panthony22** [comment]
I think I just experienced this bug. If you are on the broom when your ME buffer hits 0, it triggers this exception and kicks you from the game. If you log back in, you'll still be on the broom, but you will trigger the exception again if you press forward while the ME buffer is still at 0.

**Comment by mrsterner** [comment]
Thats on me, ill look into it

**Comment by mrsterner** [comment]
Ops jk its not my fault

**Comment by IceArrow04** [comment]
I've also been experiencing this bug, the problem only occurs in survival mode when you try to move on a broom while having no ME. It only seems to happen when BW+ is installed (Besmirchment has no effect) and it doesn't kick you when trying to ride a yew broom. I can only assume BW+ has some kind of effect on the check for ME before moving the broom relating to the yew broom's 0 ME cost implementation that causes the disconnect but I'm hardly qualified to say for certain. I've attached my [latest.log](https://github.com/MoriyaShiine/bewitchment/files/9338918/latest.log), hopefully it will help shed some light on this bug report.

**Comment by IceArrow04** [comment]
My bad my info was from 1.18.2, I didn't realize this was a 1.19 bug report at first sorry

**Comment by Bob74** [comment]
@MoriyaShiine 
Hi, I'm having the same issue with other brooms when I try moving using a broom with 0 ME on 1.18.2 (mod version 23).
It also occurs when I have enough ME to take off but run out of ME middle flight.

Here is the log, the exception seems to be raised while [reading of the boolean value](https://github.com/MoriyaShiine/bewitchment/blob/db23f6cd3af973c616bad4621d2a99edfae347c8/src/main/java/moriyashiine/bewitchment/common/network/packet/TogglePressingForwardPacket.java#L30):
```
[03:19:19] [Netty Server IO #3/ERROR]: Encountered exception while handling in channel with name "bewitchment:toggle_pressing_forward"
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 1, cap: 256))
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.PacketByteBuf.readBoolean(PacketByteBuf:1008) ~[?:?]
	at moriyashiine.bewitchment.common.network.packet.TogglePressingForwardPacket.handle(TogglePressingForwardPacket.java:30) ~[bewitchment-1.18-23.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handler$dnc000$handleCustomPayloadReceivedAsync(ServerPlayNetworkHandler:2214) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onCustomPayload(ServerPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:38) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:7) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[03:19:19] [Netty Server IO #3/ERROR]: Exception occurred in netty pipeline
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 1, cap: 256))
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.PacketByteBuf.readBoolean(PacketByteBuf:1008) ~[?:?]
	at moriyashiine.bewitchment.common.network.packet.TogglePressingForwardPacket.handle(TogglePressingForwardPacket.java:30) ~[bewitchment-1.18-23.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handler$dnc000$handleCustomPayloadReceivedAsync(ServerPlayNetworkHandler:2214) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onCustomPayload(ServerPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:38) ~[?:?]
	at net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.apply(CustomPayloadC2SPacket:7) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[03:19:19] [Server thread/INFO]: Bob_74 lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 1, cap: 256))
```

I hope this will help you!
