### ISSUE TITLE
Minecraft server Bewitchment Mod error Could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment'! Caused by: java.lang.NoSuchFieldError: TEXTURE

### ISSUE THREAD

**Issue by LeoPlayz14** [MoriyaShiine/bewitchment#414]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.16.5-12

### A description of the issue

Right im trying to help my friend out with their server and the mod isnt working and we've switch versions of it and installed origins and its still not working.

As my friend said: it didn't give any "crash-reports" so I'll be sending the logs and what the console said:

[Falix Panel]: Server is starting.
[EU2-Budget Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[EU2-Budget Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -Xms128M -Xmx5120M -Dpaper.playerconnection.keepalive=60 -Dfile.encoding=UTF-8 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[19:57:50] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.16.9
[19:57:50] [ForkJoinPool-1-worker-0/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[19:57:50] [ForkJoinPool-1-worker-0/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[19:57:50] [ForkJoinPool-1-worker-0/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[19:57:50] [ForkJoinPool-1-worker-0/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[19:57:50] [main/INFO]: Loading 66 mods:
- bewitchment 1.16.5-12
|-- playerabilitylib 1.2.1
|-- reach-entity-attributes 1.1.1
|-- step-height-entity-attribute 1.0.0
\-- terraform-wood-api-v1 1.0.4
- cloth-api 1.6.59
|-- cloth-armor-api-v1 1.6.59
|-- cloth-client-events-v0 1.6.59
|-- cloth-common-events-v1 1.6.59
|-- cloth-datagen-api-v1 1.6.59
|-- cloth-durability-bar-api-v1 1.6.59
|-- cloth-dynamic-registry-api-v1 1.6.59
|-- cloth-scissors-api-v1 1.6.59
\-- cloth-utils-v1 1.6.59
- cloth-config2 4.14.54
\-- cloth-basic-math 0.6.0
- fabric 0.42.0+1.16
|-- fabric-api-base 0.4.0+3cc0f0907d
|-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
|-- fabric-biome-api-v1 3.1.13+3cc0f0907d
|-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
|-- fabric-command-api-v1 1.1.3+3cc0f0907d
|-- fabric-commands-v0 0.2.3+3cc0f0907d
|-- fabric-containers-v0 0.1.12+3cc0f0907d
|-- fabric-content-registries-v0 0.2.5+3cc0f0907d
|-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
|-- fabric-dimensions-v1 2.0.8+3cc0f0907d
|-- fabric-entity-events-v1 1.2.4+3cc0f0907d
|-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
|-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
|-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
|-- fabric-item-api-v1 1.2.2+3cc0f0907d
|-- fabric-item-groups-v0 0.3.1+3cc0f0907d
|-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
|-- fabric-keybindings-v0 0.2.2+3cc0f0907d
|-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
|-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
|-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
|-- fabric-models-v0 0.3.1+3cc0f0907d
|-- fabric-networking-api-v1 1.0.5+3cc0f0907d
|-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
|-- fabric-networking-v0 0.3.3+3cc0f0907d
|-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
|-- fabric-object-builders-v0 0.7.3+3cc0f0907d
|-- fabric-particles-v1 0.2.5+3cc0f0907d
|-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
|-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
|-- fabric-renderer-indigo 0.4.5+3cc0f0907d
|-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
|-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
|-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
|-- fabric-rendering-v0 1.1.3+3cc0f0907d
|-- fabric-rendering-v1 1.6.1+3cc0f0907d
|-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
|-- fabric-screen-api-v1 1.0.1+3cc0f0907d
|-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
|-- fabric-structure-api-v1 1.1.12+3cc0f0907d
|-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
|-- fabric-textures-v0 1.0.7+3cc0f0907d
|-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
\-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
- fabricloader 0.16.9
\-- mixinextras 0.4.1
- impersonate 2.2.1
|-- cardinal-components-base 2.8.2
|-- cardinal-components-entity 2.8.2
\-- fabric-permissions-api-v0 0.1-SNAPSHOT
- java 8
- minecraft 1.16.5
- nourish 1.3.2
- origins 0.7.1
|-- fallflyinglib 1.1.0
\-- reach-entity-attributes 1.1.1
- patchouli 1.16.4-53-FABRIC
\-- fiber 0.23.0-2
- pehkui 2.6.0+1.14.4-1.18
\-- kanos_config 0.1.4+1.14.4-1.17.1
- somnus 0.0.12-1.16.5
- trinkets 2.6.7
[19:57:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[19:57:51] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
[19:57:51] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[19:57:55] [main/INFO]: Origins 0.7.1 is initializing. Have fun!
[19:57:56] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment' at 'moriyashiine.bewitchment.common.Bewitchment'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
at net.minecraft.server.Main.main(Main.java:92) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: TEXTURE
at moriyashiine.bewitchment.common.item.SpecterBangleItem.<clinit>(SpecterBangleItem.java:26) ~[bewitchment-1.16.5-12.jar:?]
at moriyashiine.bewitchment.common.registry.BWObjects.<clinit>(BWObjects.java:271) ~[bewitchment-1.16.5-12.jar:?]
at moriyashiine.bewitchment.common.Bewitchment.onInitialize(Bewitchment.java:212) ~[bewitchment-1.16.5-12.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]

### Log or crash report

https://mclo.gs/9Eg5ScI

**Comment by MoriyaShiine** [comment]
> Please verify that you actually read the check boxes you marked, 1.16 has been unsupported for over 3 years.

This was stated in the last issue, please stop opening issues on abandoned versions, it will not be fixed. If you want help troubleshooting, join the discord server, but the version you are running is over 3 years old.
