### ISSUE TITLE
[main/FATAL]: Error executing task on Client

### ISSUE THREAD

**Issue by armuell** [MoriyaShiine/bewitchment#44]
This gets spammed in the log and then causes the game to hang/freeze (no crashlog since it never crashes, I'm forced to kill the instance)

`[16:40:28] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 25 on entity class_746['TooGoodMules'/83551, l='ClientLevel', x=-3142.87, y=87.00, z=-1584.40]: old=bewitchment:human(class java.lang.String), new=0(class java.lang.Integer)
	at net.minecraft.class_2945.method_12785(class_2945.java:241) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:228) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:568) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:42) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:11) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: -51
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:232)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$ben000$getCollisionShape(class_4970.java:1075)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970.method_9575(class_4970.java:304)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26210(class_4970.java:723)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:39)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:45)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.flat.FlatLightPipeline.calculate(FlatLightPipeline.java:33)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
[16:40:28] [Chunk Render Task Executor #1/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: -40
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:232)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$ben000$getCollisionShape(class_4970.java:1075)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970.method_9575(class_4970.java:304)
[16:40:28] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26210(class_4970.java:723)`

Java is version 1.8.0_281, using 64-bit architecture.
Latest version of fabric loader

Mods:
  [✔️] [1.16.4]+MoreTooltips-1.0.1
  [✔️] 1.16.4-storagecabinet-1.2.0
  [✔️] Adorn-1.13.0+1.16.5
  [✔️] advancements-enlarger-0.2.3
  [✔️] Allure-1.2.8
  [✔️] AnvilFix-1.2.1-1.16
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] appliedenergistics2-fabric-8.2.0-alpha.2
  [✔️] architectury-1.8.120-fabric
  [✔️] artifacts-2.3.0+fabric
  [✔️] artofalchemy-1.0.0-rc4+1.16.4
  [✔️] astromine-1.11.5+fabric-1.16.5
  [✔️] beach-slimes-2.1.0+mc1.16.1
  [✔️] bedspreads-fabric-1.3.1-1.16.4
  [✔️] BetterCaves-fabric-1.16.2-1.0.3
  [✔️] better-end-0.9.1-pre
  [✔️] betterf3-1.1.2+1.16.2
  [✔️] BetterMineshafts-Fabric-1.16.4-1.0
  [✔️] better-nether-5.0.7
  [✔️] betterthanmending-1.3.0
  [✔️] better-wandering-trader-1.6.2
  [✔️] bewitchment-1.16.5-3
  [✔️] blame-1.16.4-2.4.1
  [✔️] blast-1.5
  [✔️] blockus-2.0.2+1.16.4
  [✔️] campanion-1.3.5
  [✔️] can-i-mine-this-block-1.0.2
  [✔️] Cardinal-Components-API-2.7.12
  [✔️] ce_foodstuffs-1.1.3
  [✔️] cinderscapes-1.3.3
  [✔️] cleancut-mc1.16-2.1-fabric
  [✔️] cloth-api-1.5.47
  [✔️] cloth-config-4.11.14-fabric
  [✔️] Controlling-For-Fabric-1.1.3
  [✔️] Couplings-1.3.6
  [✔️] crawl-0.8.2
  [✔️] crookedcrooks-1.3.3+1.16.4
  [✔️] DamageTilt-1.16-fabric-0.1.2
  [✔️] dawn-1.7
  [✔️] diggusmaximus-1.4.2-1.16.3
  [✔️] DisableCustomWorldsAdvice-1.2
  [✔️] ducts-1.0.4
  [✔️] dynamic-fps-2.0.1
  [✔️] easierenchanting-1.6.0
  [✔️] expandedstorage-5.6.33+1.16.5
  [✔️] extraalchemy-fabric-1.16.4-1.3.1
  [✔️] extraorigins-1.16.5-7
  [✔️] extremesoundmuffler-3.0.0-BETA
  [✔️] ezpas-1.2.3-1.16.2
  [✔️] fabric-api-0.31.0+1.16
  [✔️] fabric-furnaces-1.3.3-1.16.4
  [✔️] fabric-language-kotlin-1.4.30+build.2
  [✔️] fallingleaves-1.5.0+1.16.5
  [✔️] fastfurnace-2.3
  [✔️] fatxporbs-0.0.9+1.16.4
  [✔️] flesh2leather-1.0.2
  [✔️] flora-doubling-1.3.0+1.16.4-fabric
  [✔️] geckolib-fabric-1.16.5-3.0.22
  [✔️] GentleFawn-1.1.2-MC1.16.3-fabric
  [✔️] glassential-fabric-1.16.4-1.1.5
  [✔️] go-fish-1.2.1-beta-1.16.4
  [✔️] gottaclimbfast-1.0
  [✔️] gravestones-v1.9
  [✔️] grind-enchantments-1.1.3+1.16.3
  [✔️] gunpowder-base-0.3.5+1.16.5
  [✔️] gunpowder-sleepvote-1.0.3+gunpowder.0.3.1.mc.1.16.4
  [✔️] i-am-very-smart-2.1.0+mc1.16.1
  [✔️] illuminations-1.4.5
  [✔️] illuminations-uninstaller
  [✔️] Impersonate-2.1.0
  [✔️] inmis-2.1.1-1.16.4
  [✔️] InventorySorter-1.7.7-1.16
  [✔️] iron-jetpacks-0.3.1
  [✔️] itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029
  [✔️] kibe-1.16.5-1.6.3-BETA
  [✔️] lambdynamiclights-fabric-1.3.4+1.16
  [✔️] lead-villagers-2.1.0+mc1.16.1
  [✔️] light-overlay-5.8.0
  [✔️] lithium-fabric-mc1.16.5-0.6.3
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
  [✔️] megane-3.1.3+1.16.5
  [✔️] mess-1.16.x-1.0.0
  [✔️] modmenu-1.16.8
  [✔️] more-potions-1.0.1
  [✔️] mostructures-1.0.1+mc.1.16.4
  [✔️] netherite-plus-mod-1.3.17-1.16.5-forge
  [✔️] NoFog-1.16.2b1-Fabric
  [✔️] nomoreglowingpots-1.0.2
  [✔️] nookbuild-1.4.0
  [✔️] Origins-1.16.5-0.5.2
  [✔️] Origins-Classes-1.16.5-1.1.1
  [✔️] Patchouli-1.16.4-50-FABRIC
  [✔️] Pehkui-1.7.1+21w03a(1)
  [✔️] phosphor-fabric-mc1.16.3-0.7.1+build.11
  [✔️] plantinajar-1.8.1
  [✔️] pling-1.3.0
  [✔️] polymorph-fabric-0.0.9-1.16.5
  [✔️] quickshulker-1.1.14-1.16
  [✔️] randompatches-2.4.5-fabric
  [✔️] rare-ice-0.2.2
  [✔️] RebornCore-1.16-4.7.2+build.132
  [✔️] repurposed_structures-1.16.5-1.8.2
  [✔️] rer-2.1.3
  [✔️] reroll-1.2.0-1.16.5
  [✔️] RoughlyEnoughItems-5.10.183
  [✔️] selfgoverningcatalyst-1.16-1.0.5
  [✔️] shulkerboxtooltip-2.3.5+1.16.5
  [✔️] Silky-Spawners-2.1.0+build.2-1.16
  [✔️] sodium-fabric-mc1.16.3-0.1.0
  [✔️] somnus-fabric-0.0.11-1.16.5
  [✔️] staffofbuilding-1.2.5-1.16.5
  [✔️] TechReborn-1.16-3.8.1+build.211
  [✔️] terrestria-2.2.0
  [✔️] textile_backup-2.1.0-prev-1.16.4
  [✔️] the_bumblezone_fabric-1.16.5-2.3.0
  [✔️] traverse-3.3.2
  [✔️] trinkets-2.6.7
  [✔️] ublowfire-1.16-1.0.1
  [✔️] vanguard-uninstaller
  [✔️] vanillaexcavators-2.1.2-1.16.2
  [✔️] vanilla-hammers-3.0.1-1.16.3
  [✔️] vanillautomated-1.1.5
  [✔️] WhereIsIt-1.16.3-1.9.1
  [✔️] Wither-Totems-Mod-0.3.2-1.16.2
  [✔️] wraith-harvestscythes-1.0.9
  [✔️] wraith-waystones-1.1.1.1
  [✔️] wthit-2.2.1+1.16.5
  [✔️] Xaeros_Minimap_21.4.1_Fabric_1.16.5
  [✔️] XaerosWorldMap_1.12.1_Fabric_1.16.5
  [✔️] xp_storage-1.4+1.16.5
  [✔️] YungsApi-1.16.4-Fabric-1

**Comment by armuell** [comment]
Other info:

Happens when caving and/or exploring new terrain with structures nearby

**Comment by MoriyaShiine** [comment]
Can you isolate which mod causes this

**Comment by armuell** [comment]
I wasn't able to figure it out which is why I posted here for help, my guess is it is a some combo of the following mods:

- bewitchment
- sodium
- applied energistics

It's possible it's also related to mo' structures, artifacts, astromine, and techreborn (all of them add oregen/structures). This issue has been giving me nightmares. Everytime a player hangs it causes some weird form of chunk corruption/playerdata corruption that slowly lags the world until eventually the server will crash on player joins (server crashlog is useless, server loop tick spam). Running the world through the optimize tool and checking "clear world cache" seems to be a band-aid fix. Also setting smooth lighting to "off" makes the issue much less common (but still occur) so it has something to do with rendering lighting when either loading or generating chunks.

**Comment by MoriyaShiine** [comment]
Try using the binary search method (remove half of your mods at a time to find which one is causing it) because I can't figure out what the log is telling me, I'd need to actually see what mod is causing it

**Comment by armuell** [comment]
It's bewitchment and mo' structures, disabling either of those mods stops that error from happening

**Comment by Sunconure11** [comment]
Could you turn off “TooGoodMules” or whatever that came from? I have a hunch.

**Comment by armuell** [comment]
TooGoodMules and Dinneh are player names

Fresh pastebin: https://pastebin.com/fh4TtV1Y

I have some more info:
- Anything related to sodium/lighting from the original comment is unrelated (i think)
- This error is spammed in your log on world join and anytime a player is loaded (ie you load a chunk with a player in it)

**Comment by Sunconure11** [comment]
Dumb proposal, but please backup said files before doing what I'm about to suggest, should it not do anything.

Have you tried deleting player files?

**Comment by Aelpecyem** [comment]
Stop right here.

Deleting player files is not going to rectify this issue.

Can you give a full log instead?

**Comment by armuell** [comment]
latest full log: https://pastebin.com/N8ftYdQP

For the record I did "delete" all files in the advancement folder of the world before these last two comments were even made. Delete in quotes meaning I just moved them to my desktop temporarily to see if it was the cause of a server crash on player join (and it probably was since that crash went away).

**Comment by MoriyaShiine** [comment]
My guess is it's just world corruption, so I'll close it as I've never had this happen nor anyone else having it happen
